replicaCount: 1
maxUnavailable: 0

images:
  pullPolicy: IfNotPresent
  creator:
    repository: hypertrace/hypertrace-view-creator
    tagOverride: ""
  generator:
    repository: hypertrace/hypertrace-view-generator
    tagOverride: ""

imagePullSecrets: []

containerAdminPort: 8099

nodeLabels: {}

viewCreatorJobConfig:
  name: view-creator-job-config
  data:
    application.conf: |-
      pinot.retentionTimeValue = 5
      pinot.retentionTimeUnit = DAYS

allViews:
  creator:
    jobName: all-views-creation-job
    javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"
    resources:
      limits:
        cpu: 1.0
        memory: 384Mi
      requests:
        cpu: 0.1
        memory: 384Mi

logConfig:
  name: view-generator-log-config
  monitorInterval: 30
  rootLogger:
    level: INFO
  appender:
    rolling:
      enabled: false

groups:
  - name: multi-view-generator-group1
    generator:
      deploymentName: multi-view-generator-group1
      podLabels:
        app: multi-view-generator-group1
      deploymentSelectorMatchLabels:
        app: multi-view-generator-group1
      javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
      resources:
        limits:
          cpu: 1.0
          memory: 512Mi
        requests:
          cpu: 0.2
          memory: 320Mi
    viewGeneratorServiceConfig:
      name: multi-view-generator-group1-config
      viewgenerators:
        - "view-gen-backend-entity"
        - "view-gen-raw-service"
      kafka:
        streams:
          config:
            metricsRecordingLevel: INFO
            numStreamThreads: 2
            bootstrapServers: "bootstrap:9092"
            schemaRegistryUrl: "http://schema-registry-service:8081"
  - name: multi-view-generator-group2
    generator:
      deploymentName: multi-view-generator-group2
      podLabels:
        app: multi-view-generator-group2
      deploymentSelectorMatchLabels:
        app: multi-view-generator-group2
      javaOpts: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
      resources:
        limits:
          cpu: 1.0
          memory: 512Mi
        requests:
          cpu: 0.2
          memory: 320Mi
    viewGeneratorServiceConfig:
      name: multi-view-generator-group2-config
      viewgenerators:
        - "view-gen-raw-traces"
        - "view-gen-service-call"
        - "view-gen-span-event"
      kafka:
        streams:
          config:
            metricsRecordingLevel: INFO
            numStreamThreads: 2
            bootstrapServers: "bootstrap:9092"
            schemaRegistryUrl: "http://schema-registry-service:8081"

kafka-topic-creator:
  jobName: view-generation-kafka-topics-creator
  helmHook: pre-install,pre-upgrade
  kafka:
    topics:
      - name: backend-entity-view-events
        replicationFactor: 1
        partitions: 2
        configs:
          - retention.bytes=4294967296
          - retention.ms=259200000
      - name: raw-trace-view-events
        replicationFactor: 1
        partitions: 2
        configs:
          - retention.bytes=4294967296
          - retention.ms=259200000
      - name: raw-service-view-events
        replicationFactor: 1
        partitions: 2
        configs:
          - retention.bytes=4294967296
          - retention.ms=259200000
      - name: service-call-view-events
        replicationFactor: 1
        partitions: 2
        configs:
          - retention.bytes=4294967296
          - retention.ms=259200000
      - name: span-event-view
        replicationFactor: 1
        partitions: 2
        configs:
          - retention.bytes=4294967296
          - retention.ms=259200000
  zookeeper:
    address: zookeeper:2181
  imagePullSecrets: []
  podAnnotations: {}